"""Streamlit demo for the IBM Granite retrieval + RAG system.

A lightweight UI to demonstrate the retrieve-then-generate pipeline (the A+B
deliverable) with IBM Granite. The user can:

- Paste a document (or load the sample).
- Type a question (search box).
- Run the query and view the model's answer **plus the source chunks it cited**
  (the real ``RAGPipeline`` -> ``RAGResult`` flow over a Granite dense retriever
  and a Granite generative model).
- Toggle a benchmark comparison chart to see Granite vs. baselines.

Run from the project root:

    streamlit run app/main.py

This wires the **real** pipeline: the pasted document is chunked, embedded with a
Granite embedding model, indexed, and retrieved (``src.retrieval.factory``); the
answer is generated by a local Granite model (``src.llm_client.LLMClient``) via
``src.rag_pipeline.RAGPipeline``. The generative model defaults to the lightweight
``granite-4.1-3b`` (CPU-friendly; set ``GRANITE_MODEL_ID`` / ``LLM_DEVICE`` to
change). Both models download from Hugging Face on first use and are cached across
reruns with ``st.cache_resource``.
"""

from __future__ import annotations

import sys
import time
from pathlib import Path
from typing import List

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import streamlit as st

# Make the project root importable when launched via `streamlit run app/main.py`
# (Streamlit puts app/ on sys.path, not the repo root).
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.llm_client import LLMClient  # noqa: E402
from src.rag_app import build_rag_pipeline_from_text  # noqa: E402
from src.retrieval.base import RetrievedChunk  # noqa: E402


# ---------------------------------------------------------------------------
# Real retrieve-then-generate pipeline (cached so models load once)
# ---------------------------------------------------------------------------

@st.cache_resource(show_spinner=False)
def _get_llm():
    """Load the Granite generative model once (cached across reruns).

    Model id comes from ``GRANITE_MODEL_ID`` (default ``granite-4.1-3b``) and the
    device from ``LLM_DEVICE`` — see ``src/llm_client.py`` / ``.env.example``.
    """
    return LLMClient()


@st.cache_resource(show_spinner=False)
def _get_pipeline(document_text: str, top_k: int):
    """Build (and cache) a RAG pipeline over ``document_text``.

    Keyed by the document text and ``top_k``: pasting a new document rebuilds the
    index, the same document reuses it. The generative model is shared via
    :func:`_get_llm`.
    """
    return build_rag_pipeline_from_text(document_text, _get_llm(), top_k=top_k)


# ---------------------------------------------------------------------------
# Benchmark data loader + chart
# ---------------------------------------------------------------------------

def _resolve_results_dir() -> Path:
    """Find the ``results/`` directory relative to the project root."""
    candidates = [
        Path("results"),                  # running from project root
        Path(__file__).resolve().parent.parent / "results",  # from app/
    ]
    for p in candidates:
        if p.exists():
            return p
    return candidates[0]  # fallback — will show a clear error downstream


def load_benchmark_data() -> pd.DataFrame | None:
    """Load all *_fair.csv evaluation results, concat with a 'dataset' column."""
    results_dir = _resolve_results_dir()
    datasets = ["scifact", "fiqa", "nfcorpus"]
    frames = []
    for ds in datasets:
        path = results_dir / f"{ds}_fair.csv"
        if path.exists():
            df_ds = pd.read_csv(path)
            df_ds["dataset"] = ds
            frames.append(df_ds)
    if frames:
        return pd.concat(frames, ignore_index=True)
    # Fallback: try the old single-file format.
    legacy = results_dir / "benchmark_results.csv"
    if legacy.exists():
        return pd.read_csv(legacy)
    return None


def load_rag_data() -> pd.DataFrame | None:
    """Load rag_results.csv if available, else return None."""
    csv_path = _resolve_results_dir() / "rag_results.csv"
    if csv_path.exists():
        return pd.read_csv(csv_path)
    return None


def render_benchmark_chart(df: pd.DataFrame) -> None:
    """Multi-dataset grouped bar chart: headline metrics × key retrievers."""
    # Detect column name (new CSVs use 'retriever', legacy use 'model').
    id_col = "retriever" if "retriever" in df.columns else "model"

    headline = ["ndcg@10", "recall@10", "mrr"]
    available = [m for m in headline if m in df.columns and df[m].notna().any()]
    if not available:
        st.warning("No headline metrics found in benchmark data.")
        return

    key_retrievers = ["granite_dense", "bm25", "st_dense", "bge_dense", "granite_rerank"]
    present = [r for r in key_retrievers if r in df[id_col].values]
    if not present:
        present = df[id_col].unique().tolist()[:5]
    df_plot = df[df[id_col].isin(present)]

    palette = {
        "granite_dense": "#8a5cc4", "granite_rerank": "#b38add",
        "bge_dense": "#4c9f70", "st_dense": "#7eb0d5", "bm25": "#b0b0b0",
    }

    datasets = df_plot["dataset"].unique() if "dataset" in df_plot.columns else ["scifact"]
    n_ds = len(datasets)

    sns.set_theme(style="white", context="notebook")
    fig, axes = plt.subplots(1, n_ds, figsize=(6 * n_ds, 5), sharey=True)
    if n_ds == 1:
        axes = [axes]

    for ax, ds in zip(axes, datasets):
        df_ds = df_plot[df_plot["dataset"] == ds] if "dataset" in df_plot.columns else df_plot
        df_melt = df_ds.melt(id_vars=[id_col], value_vars=available,
                              var_name="metric", value_name="score")
        sns.barplot(data=df_melt, x="metric", y="score", hue=id_col,
                    palette=palette, ax=ax, legend=(ax == axes[0]))
        ax.set_title(ds.upper(), fontsize=13, weight="bold")
        ax.set_xlabel("")
        ax.set_ylabel("Score" if ax == axes[0] else "")
        ax.set_ylim(0, 1.0)
        ax.grid(axis="y", alpha=0.3)

    fig.suptitle("Retrieval Benchmark: Key Retrievers Across Datasets",
                 fontsize=14, weight="bold", y=1.02)
    plt.tight_layout()
    st.pyplot(fig)
    plt.close(fig)


def render_ablation_chart(df: pd.DataFrame) -> None:
    """Multi-dataset heatmap: all retrievers × all datasets, coloured by nDCG@10."""
    id_col = "retriever" if "retriever" in df.columns else "model"
    if "dataset" not in df.columns:
        st.info("Multi-dataset columns not available. Run A3 first.")
        return

    pivot = df.pivot_table(
        index=id_col,
        columns="dataset",
        values="ndcg@10",
        aggfunc="mean",
    )
    if pivot.empty:
        return
    pivot["avg"] = pivot.mean(axis=1)
    pivot = pivot.sort_values("avg", ascending=False).drop(columns="avg")

    sns.set_theme(style="white", context="notebook")
    fig, ax = plt.subplots(figsize=(8, max(5, len(pivot) * 0.4)))
    sns.heatmap(
        pivot,
        annot=True,
        fmt=".3f",
        cmap="RdYlGn",
        vmin=0.15,
        vmax=0.80,
        linewidths=0.5,
        linecolor="white",
        cbar_kws={"label": "nDCG@10"},
        ax=ax,
    )
    ax.set_title("nDCG@10: All Retrievers × All Datasets", fontsize=13, weight="bold")
    ax.set_xlabel("")
    ax.set_ylabel("")
    plt.tight_layout()
    st.pyplot(fig)
    plt.close(fig)


def render_rag_chart(df_rag: pd.DataFrame) -> None:
    """Draw RAG quality charts from rag_results.csv."""
    rag_metrics = ["answer_correctness", "context_precision", "faithfulness"]
    available = [m for m in rag_metrics if m in df_rag.columns]
    if not available:
        st.warning("No RAG metric columns found in rag_results.csv.")
        return

    sns.set_theme(style="white", context="notebook")

    # Chart 1 — RAG quality by retriever (top_k=4).
    st.markdown("#### RAG Quality by Retriever (top‑k=4)")
    df_tk4 = df_rag[df_rag["top_k"] == 4] if "top_k" in df_rag.columns else df_rag
    if not df_tk4.empty:
        df_rm = df_tk4.melt(id_vars=["model"], value_vars=available,
                             var_name="metric", value_name="score")
        fig, ax = plt.subplots(figsize=(7, 4))
        pal = {"granite_rag": "#8a5cc4", "st_rag": "#7eb0d5", "bm25_rag": "#b0b0b0"}
        sns.barplot(data=df_rm, x="metric", y="score", hue="model",
                    palette=pal, ax=ax)
        ax.set_title("RAG Quality: Correctness / Context Precision / Faithfulness",
                     fontsize=12, weight="bold")
        ax.set_xlabel("")
        ax.set_ylabel("Score")
        ax.set_ylim(0, 1.0)
        ax.legend(title="Pipeline", frameon=True)
        ax.grid(axis="y", alpha=0.3)
        for container in ax.containers:
            ax.bar_label(container, fmt="%.2f", fontsize=8)
        plt.tight_layout()
        st.pyplot(fig)
        plt.close(fig)

    # Chart 2 — Top‑k sweep for Granite RAG.
    if "top_k" in df_rag.columns and "granite_rag" in df_rag["model"].values:
        st.markdown("#### Top‑k Sweep (Granite RAG)")
        df_tk = df_rag[df_rag["model"] == "granite_rag"].sort_values("top_k")
        if len(df_tk) >= 2:
            fig, ax = plt.subplots(figsize=(6, 4))
            for m in available:
                ax.plot(df_tk["top_k"], df_tk[m], marker="o", linewidth=2, label=m)
            ax.set_title("RAG: Top‑k vs. Quality (Granite RAG)", fontsize=12, weight="bold")
            ax.set_xlabel("Top‑k retrieved chunks")
            ax.set_ylabel("Score")
            ax.set_ylim(0.6, 1.0)
            ax.legend(frameon=True)
            ax.grid(True, alpha=0.3)
            plt.tight_layout()
            st.pyplot(fig)
            plt.close(fig)


# ---------------------------------------------------------------------------
# Session state init
# ---------------------------------------------------------------------------

def _init_session() -> None:
    """One-time initialisation of Streamlit session state."""
    defaults = {
        "document_text": "",
        "last_query": "",
        "last_answer": "",
        "last_chunks": [],
        "show_results": False,
    }
    for key, val in defaults.items():
        if key not in st.session_state:
            st.session_state[key] = val


# ---------------------------------------------------------------------------
# UI helpers
# ---------------------------------------------------------------------------

SAMPLE_DOC = (
    "CONFIDENTIAL — Internal Use Only\n\n"
    "Q4 Financial Summary: Revenue reached $42.3M, up 18% YoY. "
    "Operating margin improved to 24%.\n\n"
    "Project Nightingale Update: The secret launch code is ECHO-42. "
    "Launch window: March 15. Access restricted to core team only.\n\n"
    "Security Audit (February): Three medium-severity issues in the "
    "auth service. Patches in progress. Core infrastructure is clean.\n\n"
    "ML Pipeline Results: Granite 8B dense encoder achieved 94.3% "
    "accuracy, beating the Sentence-BERT baseline by 6.8 pp.\n\n"
    "Employee Survey: 87% satisfaction. Top request: flexible hours "
    "and better remote-work tools.\n\n"
    "Cloud Costs: Infrastructure spend down 12% after Kubernetes "
    "migration. Further optimisation planned for Q1.\n\n"
    "Customer Support: Ticket volume down 30% after self-service KB "
    "launch. Password resets still account for 45% of remaining tickets.\n\n"
    "Company Retreat: Lisbon, June 10–14. Workshop proposals due May 1."
)


def _render_sidebar() -> None:
    """Draw the settings sidebar."""
    with st.sidebar:
        st.header("⚙️ Settings")
        st.selectbox(
            "Model",
            options=["IBM Granite 8B", "Baseline — Sentence-BERT", "BM25 (sparse)"],
            help="Display only for now — the demo runs the Granite dense retriever "
                 "+ Granite generator (set GRANITE_MODEL_ID to change the generator).",
            key="model_choice",
        )
        st.slider(
            "Max new tokens",
            min_value=32,
            max_value=1024,
            value=256,
            step=32,
            help="Display only for now — generation uses LLMClient's default config.",
            key="max_tokens",
        )
        st.slider(
            "Top‑k chunks",
            min_value=1,
            max_value=8,
            value=4,
            step=1,
            help="How many retrieved chunks to pass to the generator as context.",
            key="top_k",
        )
        st.divider()
        st.checkbox(
            "📊 Show benchmark (real HPC)",
            value=False,
            key="show_benchmark",
            help="Baseline comparison: Granite Dense vs. BM25 / ST Dense on SciFact.",
        )
        st.checkbox(
            "🔬 Show multi-dataset overview",
            value=False,
            key="show_ablation",
            help="All-retrievers × all-datasets heatmap of nDCG@10.",
        )
        st.checkbox(
            "🤖 Show RAG results",
            value=False,
            key="show_rag",
            help="Answer correctness, context precision, faithfulness "
                 "from rag_results.csv.",
        )


def _render_document_input() -> None:
    """Section 1: document / haystack input."""
    st.subheader("1. Provide a document (haystack)")

    c_left, c_right = st.columns([1, 1])
    with c_left:
        uploaded_file = st.file_uploader(
            "Upload a text document",
            type=["txt", "md"],
            help="Upload is not wired yet — paste the document text below or click "
                 "'Load sample document'.",
            key="uploaded_file",
        )
    with c_right:
        if st.button("📋 Load sample document", use_container_width=True):
            st.session_state.document_text = SAMPLE_DOC

    st.text_area(
        "...or paste text directly",
        height=200,
        placeholder="Paste the long document here, or click 'Load sample document'.",
        key="document_text",
    )


def _set_query(text: str) -> None:
    """Fill the question box. Used as a button ``on_click`` so it runs *before*
    the text_input widget is re-instantiated; setting ``last_query`` inline after
    the widget already exists raises a StreamlitAPIException."""
    st.session_state.last_query = text


def _render_query_input() -> None:
    """Section 2: query input."""
    st.subheader("2. Ask a question (find the needle)")
    col_q, col_btn = st.columns([3, 1])
    with col_q:
        st.text_input(
            "Question",
            placeholder="e.g. What is the secret launch code?",
            key="last_query",
            label_visibility="collapsed",
        )
    with col_btn:
        run = st.button("🔍 Search", type="primary", use_container_width=True)

    # Quick-pick examples.
    st.caption("Try these:")
    examples = [
        "What is the secret launch code?",
        "How did revenue perform in Q4?",
        "Were any security vulnerabilities found?",
        "What accuracy did the ML pipeline achieve?",
        "What was employee satisfaction?",
    ]
    cols = st.columns(len(examples))
    for i, ex in enumerate(examples):
        with cols[i]:
            st.button(
                ex[:28] + "…" if len(ex) > 28 else ex,
                key=f"ex_{i}",
                on_click=_set_query,
                args=(ex,),
            )

    if run and not st.session_state.get("last_query"):
        st.warning("Please enter a question.")
        st.stop()

    return run


def _render_results(chunks: List[RetrievedChunk], answer: str, elapsed: float) -> None:
    """Section 3: RAG results — answer + cited source chunks."""
    st.divider()
    st.subheader("3. Results")
    st.caption(f"Retrieved {len(chunks)} chunks and generated an answer in "
               f"{elapsed:.1f}s.")

    # --- Answer ---
    st.markdown("### 💬 Answer")
    st.markdown(answer)

    # --- Cited sources ---
    if not chunks:
        st.info("No relevant chunks were retrieved from the document.")
        return

    st.markdown("### 📎 Cited sources")
    for i, chunk in enumerate(chunks):
        with st.expander(f"[{i + 1}] {chunk.doc_id}  —  score {chunk.score:.3f}"):
            st.text(chunk.text)


def _render_evaluation_section() -> None:
    """Render benchmark / ablation / RAG charts based on sidebar toggles."""
    show_bench = st.session_state.get("show_benchmark", False)
    show_ablation = st.session_state.get("show_ablation", False)
    show_rag = st.session_state.get("show_rag", False)

    if not (show_bench or show_ablation or show_rag):
        return

    st.divider()
    st.subheader("📈 Evaluation Results")

    df_bench = load_benchmark_data()
    if show_bench:
        st.markdown("### 📊 Benchmark: System vs. Baselines")
        if df_bench is not None:
            render_benchmark_chart(df_bench)
            st.caption(
                "Real HPC results from `results/benchmark_results.csv` "
                "(source=real). Granite Dense nDCG@10 = 0.767 vs. BM25 0.636."
            )
        else:
            st.warning(
                "`results/benchmark_results.csv` not found. "
                "Run `python -m eval.run_benchmark` first, or create mock data."
            )

    if show_ablation:
        st.markdown("### 🔬 Multi-Dataset Overview")
        if df_bench is not None and "dataset" in df_bench.columns:
            render_ablation_chart(df_bench)
            st.caption(
                "All retrievers × all datasets from `results/*_fair.csv` "
                "(generated by `python -m eval.run_benchmark`)."
            )
        else:
            st.info(
                "Multi-dataset `*_fair.csv` files not found. "
                "Run `python -m eval.run_benchmark --dataset scifact,fiqa,nfcorpus`."
            )

    if show_rag:
        st.markdown("### 🤖 RAG Quality")
        df_rag = load_rag_data()
        if df_rag is not None:
            render_rag_chart(df_rag)
            st.caption(
                "Mock RAG data from `results/rag_results.csv` — "
                "real data pending B1 (rag_metrics) + B2 (run_rag)."
            )
        else:
            st.warning(
                "`results/rag_results.csv` not found. "
                "Run `python -m eval.run_rag` first, or create mock data."
            )


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

def main() -> None:
    """Render the Streamlit demo app."""
    st.set_page_config(
        page_title="Needle in a Haystack — IBM Granite",
        page_icon="🪡",
        layout="wide",
    )
    _init_session()

    st.title("🪡 Needle in a Haystack — IBM Granite")
    st.caption(
        "Retrieve relevant passages, generate a grounded answer with citations "
        "(RAG), and compare retriever performance — all in one demo."
    )

    _render_sidebar()
    _render_document_input()
    triggered = _render_query_input()

    # --- Run the real retrieve-then-generate pipeline ----------------- #
    if triggered:
        question = st.session_state.last_query
        document_text = st.session_state.get("document_text", "")
        top_k = st.session_state.get("top_k", 4)

        if not document_text.strip():
            st.warning("Please provide a document first — paste text above or click "
                       "'Load sample document'.")
            st.stop()

        t0 = time.perf_counter()
        try:
            with st.spinner("Indexing your document (first run downloads the Granite "
                            "embedding model)..."):
                pipeline = _get_pipeline(document_text, top_k)
            with st.spinner("Retrieving and generating with Granite..."):
                result = pipeline.query(question)
        except Exception as exc:  # noqa: BLE001 - surface a friendly UI error
            st.error(
                "The pipeline failed to run. On the first run the Granite models "
                "download from Hugging Face, which can take a while.\n\n"
                f"Details: {exc}"
            )
            st.stop()
        elapsed = time.perf_counter() - t0
        _render_results(result.retrieved_chunks, result.answer, elapsed)

    # --- Evaluation charts (benchmark / ablation / RAG) ---------------- #
    _render_evaluation_section()


if __name__ == "__main__":
    main()
